---
- name: Get all avtive user
  become: yes
  hosts: linux
  tasks:
  - name: Active users
    shell: w
    register: users
  - name: save data to out file
    copy:
      dest: "/tmp/ansible-users-log.out"
      content: {{users}} 
