---
- name: Get all avtive user
  become: yes
  hosts: linux
  tasks:
  - name: Active users
    shell: w
    register: users
    module: copy
    content: "{{users}}"
    dest: /tmp/ansible-users-log.out
