---

- name: Get server uptime
  hosts: linux
  tasks:
    - name: Get uptime
      shell: uptime
      register: var
    - debug: msg="{{var.stdout}}"
    - debug: msg="{{var.stderr}}"
    - name: Get date
      shell: date
      register: var2
    - debug: msg="{{var2.stdout}}"
    - debug: msg="{{var2.stderr}}"