---
- name: OpenVPN Install and configuriation
  become: yes
  hosts: VPN
  vars:
    easyrsa: "https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz"
    easyrsa_dest: "/root/"
  tasks:
 # - name: Update
 #   yum:
  #    name: '*'
  #    state: latest
   # register: result2

  #- name: EPEL install
   # yum:
    #  name: epel-release
     # state: latest
 
  #- name: Install OpenVPN package
    #yum:
      #name: openvpn
      #state: latest
    #register: yum_openvpn

  - name: Get EasyRSA files
    ansible.builtin.get_url:
      url: "{{easyrsa}}"
      dest: "{{easyrsa_dest}}"
      mode: '0744'
      owner: root
      group: root
  
  - name: Uncompress EasyRSA archive
    ansible.builtin.unarchive:
      src: "EasyRSA-3.0.8.tgz"
      dest: "{{easyrsa_dest}}"
      mode: '0744'
  
  - debug:
       var: yum_openvpn.results

