---
- name: OpenVPN Install and configuriation
  become: yes
  hosts: VPN
  vars:
    easyrsa: "https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz"
    easyrsa_dest: "/root/"
    archive_file: "/root/EasyRSA-3.0.8.tgz"
  tasks:
 # - name: Update
 #   yum:
  #    name: '*'
  #    state: latest
   # register: result2

  #- name: EPEL install
   # yum:
    #  name: epel-release
     # state: latest
 
  #- name: Install OpenVPN package
    #yum:
      #name: openvpn
      #state: latest
    #register: yum_openvpn

  - name: Get EasyRSA files
    ansible.builtin.get_url:
      url: "{{easyrsa}}"
      dest: "{{easyrsa_dest}}"
      mode: '0777'
      owner: root
      group: root
  
  - name: Uncompress EasyRSA archive
    ansible.builtin.unarchive:
      src: "{{item}}"
      dest: "{{easyrsa_dest}}"
      mode: '0744'
      remote_src: yes
    with_items:
      - "{{ archive_file }}"

  - name: Copy vars to remote
    copy:
      src: ~/Linux/ansible/vars
      dest: /root/EasyRSA-3.0.8/
      owner: root
      group: root
      mode: '0644'
  
  - name: Run init-pki script
    script:
      free_form: /root/EasyRSA-3.0.8/easyrsa init-pki
      remote_src: yes

  - debug:
       var: yum_openvpn.results

