--- 
- 
  become: true
  hosts: VPN
  name: "OpenVPN Install and configuriation"
  tasks:
    -
      name: EPEL install
      yum:
       name: epel-release
       state: latest
    - 
      name: Install OpenVPN package
      yum:
       name: openvpn
       state: latest
    -
      name: "Install python pip package"
      yum:
        name: python-pip
        state: latest
    - 
      ansible.builtin.get_url: 
        dest: "{{easyrsa_dest}}"
        group: root
        mode: "0777"
        owner: root
        url: "{{easyrsa}}"
      name: "Get EasyRSA files"
    - 
      ansible.builtin.unarchive: 
        dest: "{{easyrsa_dest}}"
        mode: "0744"
        remote_src: true
        src: "{{item}}"
      name: "Uncompress EasyRSA archive"
      with_items: 
        - "{{ archive_file }}"
        
    - 
      copy: 
        dest: /root/EasyRSA-3.0.8/
        group: root
        mode: "0644"
        owner: root
        src: ~/Linux/ansible/vars
      name: "Copy vars to remote"
    -
      name: "Check if PKI dir exists"
      stat:
        path: "{{ working_dir }}pki"
      register: pki_dir

    - 
      name: "Run init-pki script"
      command: "sh {{ working_dir }}easyrsa init-pki"
      args:
        chdir: "{{ working_dir }}"
      when: not pki_dir.stat.exists
    - 
      name: "Install requied python packages"
      pip:
        name:
          - setuptools
          - pexpect
    -
      name: "Check if CA cert exists"
      stat:
        path: "{{ working_dir }}pki/private/ca.key"
      register: CA_cert     
    - 
      name: "Build CA"
      ansible.builtin.expect:
        command: "sh {{ working_dir }}easyrsa build-ca nopass"
        responses:
         'Common Name \(eg: your user, host, or server name\) \[Easy-RSA CA\]:': '{{ server_name }}'
        echo: true
      args:
          chdir: "{{ working_dir }}"
      register: build_ca
      when: not CA_cert.stat.exists
    -
      name: "Check if server key exists"
      stat:
        path: "{{ working_dir }}pki/private/{{server_name}}.key"
      register: server_cert 
    - 
       name: "Create a server key and request"
       ansible.builtin.expect:
         command: "sh {{ working_dir }}easyrsa  gen-req {{ server_name }} nopass"
         responses:
           'Common Name \(eg: your user, host, or server name\)': '{{ server_name }}'
         echo: true
       args:
         chdir: "{{ working_dir }}"
       when: not server_cert.stat.exists
    #-
     #  name: "Import server request"
      # command: "sh {{ working_dir }}easyrsa  import-req /etc/openvpn/server/{{ server_name }}.req {{ server_name }}"
       #args:
        #chdir: "{{ working_dir }}"
    -
       name: "Sign server request"
       ansible.builtin.expect:
         command: "sh {{ working_dir }}easyrsa  sign-req server {{ server_name }}"
         responses:
           'Confirm request details:': 'yes'
         echo: true
       args:
        chdir: "{{ working_dir }}"
    -
       name: "Generate strong Diffie-Hellman key and HMAC signature"
       command: "{{ item }}" 
       with_items:
         - "sh {{ working_dir }}easyrsa  gen-dh"
         - "openvpn --genkey --secret ta.key"
       args:
        chdir: "{{ working_dir }}"
    -
       name: "Copy necessary files to OpenVPN config directory"
       copy: 
         src: "{{ item.src }}"
         dest: "{{ item.dest }}"
         remote_src: true
       loop:
         - {src: '{{working_dir}}pki/ca.crt', dest: '/etc/openvpn/server'}
         - {src: '{{working_dir}}pki/issued/{{server_name}}.crt', dest: '/etc/openvpn/server'}
         - {src: '{{working_dir}}pki/private/{{server_name}}.key', dest: '/etc/openvpn/server'}
         - {src: '{{working_dir}}pki/dh.pem', dest: '/etc/openvpn/server'}
         - {src: '{{working_dir}}ta.key', dest: '/etc/openvpn/server'}      
         - {src: /usr/share/doc/openvpn-2.4.12/sample/sample-config-files/server.conf, dest: '/etc/openvpn/server'}

    - 
       name: "Set config file"
       lineinfile:
         path: /etc/openvpn/server/server.conf
         regexp: "{{item.regexp}}" # '^(.*)cert server.crt(.*)$'
         line: "{{item.line}}" #'cert {{server_name}}.crt'
       loop:
         - { regexp: '^(.*)cert server.crt(.*)$', line: 'cert {{server_name}}.crt'}
         - { regexp: '^(.*)key server.key(.*)$', line: 'key {{server_name}}.key'}
         - { regexp: '^(.*);user nobody(.*)$', line: 'user nobody'}
         - { regexp: '^(.*);group nobody(.*)$', line: 'group nobody'}

  vars: 
    archive_file: /root/EasyRSA-3.0.8.tgz
    easyrsa: "https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz"
    easyrsa_dest: /root/
    server_name: "rose"
    working_dir: "/root/EasyRSA-3.0.8/"
