--- 
- 
  become: true
  hosts: VPN
  name: "OpenVPN Install and configuriation"
  tasks: 
    - 
      ansible.builtin.get_url: 
        dest: "{{easyrsa_dest}}"
        group: root
        mode: "0777"
        owner: root
        url: "{{easyrsa}}"
      name: "Get EasyRSA files"
    - 
      ansible.builtin.unarchive: 
        dest: "{{easyrsa_dest}}"
        mode: "0744"
        remote_src: true
        src: "{{item}}"
      name: "Uncompress EasyRSA archive"
      with_items: 
        - "{{ archive_file }}"
    - 
      copy: 
        dest: /root/EasyRSA-3.0.8/
        group: root
        mode: "0644"
        owner: root
        src: ~/Linux/ansible/vars
      name: "Copy vars to remote"
    -
      name: "Check PKI dir if it exists"
      stat:
        path: "/root/EasyRSA-3.0.8/pki"
      register: pki_dir

    - 
      name: "Run init-pki script"
      command: "sh /root/EasyRSA-3.0.8/easyrsa init-pki"
      args:
        chdir: EasyRSA-3.0.8/
      when: not pki_dir.stat.exists
    - 
      name: "install Pexpect"
      pip: 
        name: pexpect
    - 
      name: "Build CA"
      ansible.builtin.expect:
        command: "sh /root/EasyRSA-3.0.8/easyrsa build-ca nopass"
        responses:
          Question:
            - "{{ resposne_1 }}"
      args:
          chdir: EasyRSA-3.0.8/
      register: build_ca
    - 
      debug: 
        var: build_ca.results
  vars: 
    archive_file: /root/EasyRSA-3.0.8.tgz
    easyrsa: "https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz"
    easyrsa_dest: /root/
    resposne_1: "server"
