--- 
- 
  become: true
  hosts: VPN
  name: "OpenVPN Install and configuriation"
  tasks:
    -
      name: EPEL install
      yum:
       name: epel-release
       state: latest
    - 
      name: Install OpenVPN package
      yum:
       name: openvpn
       state: latest
    -
      name: "Install python pip package"
      yum:
        name: python-pip
        state: latest
    - 
      ansible.builtin.get_url: 
        dest: "{{easyrsa_dest}}"
        group: root
        mode: "0777"
        owner: root
        url: "{{easyrsa}}"
      name: "Get EasyRSA files"
    - 
      ansible.builtin.unarchive: 
        dest: "{{easyrsa_dest}}"
        mode: "0744"
        remote_src: true
        src: "{{item}}"
      name: "Uncompress EasyRSA archive"
      with_items: 
        - "{{ archive_file }}"
    - 
      copy: 
        dest: /root/EasyRSA-3.0.8/
        group: root
        mode: "0644"
        owner: root
        src: ~/Linux/ansible/vars
      name: "Copy vars to remote"
    -
      name: "Check if PKI dir exists"
      stat:
        path: "{{ working_dir }}pki"
      register: pki_dir

    - 
      name: "Run init-pki script"
      command: "sh {{ working_dir }}easyrsa init-pki"
      args:
        chdir: "{{ working_dir }}"
      when: not pki_dir.stat.exists
    - 
      name: "Install requied python packages"
      pip:
        name:
          - setuptools
          - pexpect
    -
      name: "Check if CA cert exists"
      stat:
        path: "{{ working_dir }}pki/private/ca.key"
      register: CA_cert     
    - 
      name: "Build CA"
      ansible.builtin.expect:
        command: "sh {{ working_dir }}easyrsa build-ca nopass"
        responses:
         'Common Name \(eg: your user, host, or server name\) \[Easy-RSA CA\]:': '{{ server_name }}'
        echo: true
      args:
          chdir: "{{ working_dir }}"
      register: build_ca
      when: not CA_cert.stat.exists
    -
      name: "Check if server key exists"
      stat:
        path: "{{ working_dir }}pki/private/{{server_name}}.key"
      register: server_cert 
    - 
       name: "Create a server key"
       ansible.builtin.expect:
         command: "sh {{ working_dir }}easyrsa  gen-req {{ server_name }} nopass"
         responses:
           'Common Name \(eg: your user, host, or server name\)': '{{ server_name }}'
         echo: true
       args:
         chdir: "{{ working_dir }}"
       when: not server_cert.stat.exists
    -
       name: "Copy server key and requiest to OpenVPN config directory"
       copy:
         src: "{{working_dir}}pki/private/{{server_name}}.key"
         dest: "/etc/" 
    - 
      debug: 
        var: build_ca.results
  vars: 
    archive_file: /root/EasyRSA-3.0.8.tgz
    easyrsa: "https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz"
    easyrsa_dest: /root/
    server_name: "rose"
    working_dir: "/root/EasyRSA-3.0.8/"
