--- 
- 
  become: true
  hosts: VPN
  name: "OpenVPN Install and configuriation"
  tasks:
    -
      name: "Install python pip package"
      yum:
        name: python-pip
        state: latest
    - 
      ansible.builtin.get_url: 
        dest: "{{easyrsa_dest}}"
        group: root
        mode: "0777"
        owner: root
        url: "{{easyrsa}}"
      name: "Get EasyRSA files"
    - 
      ansible.builtin.unarchive: 
        dest: "{{easyrsa_dest}}"
        mode: "0744"
        remote_src: true
        src: "{{item}}"
      name: "Uncompress EasyRSA archive"
      with_items: 
        - "{{ archive_file }}"
    - 
      copy: 
        dest: /root/EasyRSA-3.0.8/
        group: root
        mode: "0644"
        owner: root
        src: ~/Linux/ansible/vars
      name: "Copy vars to remote"
    -
      name: "Check PKI dir if it exists"
      stat:
        path: "/root/EasyRSA-3.0.8/pki"
      register: pki_dir

    - 
      name: "Run init-pki script"
      command: "sh /root/EasyRSA-3.0.8/easyrsa init-pki"
      args:
        chdir: EasyRSA-3.0.8/
      when: not pki_dir.stat.exists
    - 
      name: "Install requied python packages"
      pip:
        name:
          - setuptools
          - pexpect
    -
      name: "Check CA cert if exists"
      stat:
        path: "/root/EasyRSA-3.0.8/pki/private/ca.key"
      register: CA_cert     
    - 
      name: "Build CA"
      ansible.builtin.expect:
        command: "sh /root/EasyRSA-3.0.8/easyrsa build-ca nopass"
        responses:
         'Common Name \(eg: your user, host, or server name\) \[Easy-RSA CA\]:': '{{ server_name }}'
        echo: true
      args:
          chdir: EasyRSA-3.0.8/
      register: build_ca
      when: not CA_cert.stat.exists
    
    -
      name: "Create a server key"
      command: "sh /root/EasyRSA-3.0.8/easyrsa  gen-req {{ server_name }} nopass"
      responses:
         ? "Common Name \\(eg: your user, host, or server name\\) \\['{{ server_name }}'\\]:": '{{ server_name }}'
      args:
          chdir: "{{ working_dir }}"
    - 
      debug: 
        var: build_ca.results
  vars: 
    archive_file: /root/EasyRSA-3.0.8.tgz
    easyrsa: "https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.8/EasyRSA-3.0.8.tgz"
    easyrsa_dest: /root/
    server_name: "rose"
    working_dir: "~/EasyRSA-3.0.8/"
