--- 
- 
  become: true
  hosts: TEST_ROUND #ALL_LINUX_SERVERS
  name: "Collect Patch Packages on ALL SERVERS"
  gather_facts: true
  vars:
   patch:
    - "{{ patch_list }}"

  tasks:
   - name: Get packages collection.
     yum: list=updates update_cache=true
     register: result

   - name: Save data to Servers
     copy:
       dest: "Packages.patch"
       #content: "{{ result.results | map(attribute='envra' | list)}}"
       content: "{{ result | json_query('results[*].envra')}}"

   - name: Read patch file
     ansible.builtin.slurp:
      src: /root/Packages.patch
     register: patch_list

   - set_fact:
       Packages: "{{ (patch_list.content|b64decode|from_json)}}"

   - name: Print returned information
     ansible.builtin.debug:
       msg: "{{ result }}"

   - name: Update packages
     ansible.builtin.yum:
       name: "{{ item }}"
     with_items: "{{ Packages }}"

