--- 
- 
  become: true
  hosts: ALL_LINUX_SERVERS
  name: "Collect Patch Packages on ALL SERVERS"
  gather_facts: true

  tasks:
   - name: Get packages collection.
     yum: list=updates update_cache=true
     register: result

   - name: Save data to Servers
     copy:
       dest: "Packages.patch"
       #content: "{{ result.results | map(attribute='envra' | list)}}"
       content: "{{ result.results | json_query('results[*].name')}}"
  