--- 
- 
  become: true
  hosts: ALL_LINUX_SERVERS
  name: "Collect Patch Packages on ALL SERVERS"
  gather_facts: true
  vars:
   patch:
    - "{{ patch_list }}"

  tasks:
   - name: Get packages collection.
     yum: list=updates update_cache=true
     register: result

   - name: Save data to Servers
     copy:
       dest: "Packages.patch"
       #content: "{{ result.results | map(attribute='envra' | list)}}"
       content: "{{ result | json_query('results[*].envra')}}"

   - name: Read patch file
     ansible.builtin.slurp:
      src: /root/Packages.patch
     register: patch_list

  # - name: Print returned information
  #   ansible.builtin.debug:
  #     msg: "{{ mounts['content'].envra | b64decode }}"

   - set_fact:
       Patch_fact: "{{ (patch_list.content|b64decode|from_json)}}"

   - name: Print returned information
     ansible.builtin.debug:
       msg: "{{ Patch_fact }}"

   #- name: loop through items
    # debug: 
     #  var: item
     #loop: "{{ patch | b64decode }}"

