--- 
- 
  become: true
  hosts: ALL_LINUX_SERVERS
  name: "Collect Patch Packages on ALL SERVERS"
  gather_facts: true

  tasks:
   - name: Get packages collection.
     yum: list=updates update_cache=true
     register: result

   - name: Save data to Servers
     copy:
       dest: "Packages.patch"
       #content: "{{ result.results | map(attribute='envra' | list)}}"
       content: "{{ result | json_query('results[*].envra')}}"

   - name: Read patch file
     ansible.builtin.slurp:
      src: /root/Packages.patch
     register: patch_list

  # - name: Print returned information
  #   ansible.builtin.debug:
  #     msg: "{{ mounts['content'].envra | b64decode }}"
  vars:
   patch:
    - "{{ patch_list }}"

   - name: loop through items
     debug: 
      var: item
     loop: "{{ patch }}"

