--- 
- 
  become: true
  hosts: ALL_LINUX_SERVERS
  name: "Collect Patch Packages on ALL SERVERS"
  gather_facts: true

  tasks:
   - name: Get packages collection.
     yum: list=updates update_cache=true
     register: result

   - debug:
      var: result